---
abstract: 'Perl based data store for the ANEW - standardised'
author:
  - 'Kieren Diment <zarquon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-EN-AffectiveNorms
no_index:
  directory:
    - examples
    - inc
    - share
    - t
requires:
  DBIx::Class::Schema::Loader: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
